import { useEffect, useRef, useState } from 'react'
import ReactMarkdown from 'react-markdown'

interface InsightsPanelProps {
  owner: string
  repo: string
  token: string
  days: number
}

type StreamStatus = 'analyzing' | 'streaming' | 'complete' | 'error'

function InsightsPanel({ owner, repo, token, days }: InsightsPanelProps) {
  const [content, setContent] = useState('')
  const [status, setStatus] = useState<StreamStatus>('analyzing')
  const abortRef = useRef<AbortController | null>(null)

  async function openStream() {
    abortRef.current?.abort()
    const controller = new AbortController()
    abortRef.current = controller
    setContent('')
    setStatus('analyzing')

    try {
      const url = `/api/insights?owner=${encodeURIComponent(owner)}&repo=${encodeURIComponent(repo)}&days=${days}`
      const res = await fetch(url, {
        headers: { Authorization: `Bearer ${token}` },
        signal: controller.signal,
      })

      if (!res.ok || !res.body) {
        setStatus('error')
        return
      }

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      setStatus('streaming')

      let buffer = ''
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buffer += decoder.decode(value, { stream: true })
        const parts = buffer.split('\n\n')
        buffer = parts.pop() ?? ''
        for (const part of parts) {
          for (const line of part.split('\n')) {
            if (line.startsWith('data: ')) {
              setContent(prev => prev + line.slice(6))
            }
          }
        }
      }
      setStatus('complete')
    } catch (e) {
      if ((e as Error).name !== 'AbortError') {
        setStatus(prev => prev === 'streaming' ? 'complete' : 'error')
      }
    }
  }

  useEffect(() => {
    openStream()
    return () => { abortRef.current?.abort() }
  }, [owner, repo, token, days])

  return (
    <div
      style={{
        background: '#f0f7ff',
        borderRadius: 8,
        padding: '1.5rem',
        marginTop: '1.5rem',
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h2 style={{ margin: 0, fontSize: '1.1rem' }}>✨ AI Insights</h2>
        <button
          onClick={openStream}
          style={{
            background: 'none',
            border: '1px solid #3b82f6',
            color: '#3b82f6',
            borderRadius: 6,
            padding: '0.25rem 0.75rem',
            cursor: 'pointer',
            fontSize: '0.875rem',
          }}
        >
          Regenerate
        </button>
      </div>

      {status === 'analyzing' && (
        <>
          <style>{`@keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }`}</style>
          <p style={{ color: '#6b7280', fontStyle: 'italic', animation: 'pulse 1.5s ease-in-out infinite' }}>Analyzing your metrics...</p>
        </>
      )}

      {(status === 'streaming' || status === 'complete') && (
        <div>
          <ReactMarkdown>{content}</ReactMarkdown>
          {status === 'complete' && (
            <p style={{ fontSize: '0.75rem', color: '#6b7280', marginTop: '1rem' }}>
              Generated by Claude
            </p>
          )}
        </div>
      )}

      {status === 'error' && (
        <p style={{ color: '#ef4444' }}>AI insights are currently unavailable.</p>
      )}
    </div>
  )
}

export default InsightsPanel
