import { useEffect, useRef, useState } from 'react'
import ReactMarkdown from 'react-markdown'

interface InsightsPanelProps {
  owner: string
  repo: string
  token: string
  days: number
}

type StreamStatus = 'analyzing' | 'streaming' | 'complete' | 'error'

function InsightsPanel({ owner, repo, token, days }: InsightsPanelProps) {
  const [content, setContent] = useState('')
  const [status, setStatus] = useState<StreamStatus>('analyzing')
  const evtSourceRef = useRef<EventSource | null>(null)

  function openStream() {
    evtSourceRef.current?.close()
    setContent('')
    setStatus('analyzing')

    const url = `/api/insights?owner=${encodeURIComponent(owner)}&repo=${encodeURIComponent(repo)}&token=${encodeURIComponent(token)}&days=${days}`
    const es = new EventSource(url)
    evtSourceRef.current = es

    es.onmessage = (event: MessageEvent) => {
      setContent(prev => prev + event.data)
      setStatus('streaming')
    }

    es.onerror = () => {
      setStatus(prev => (prev === 'streaming' ? 'complete' : 'error'))
      es.close()
    }
  }

  useEffect(() => {
    openStream()
    return () => {
      evtSourceRef.current?.close()
    }
  }, [owner, repo, token, days])

  return (
    <div
      style={{
        background: '#f0f7ff',
        borderRadius: 8,
        padding: '1.5rem',
        marginTop: '1.5rem',
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h2 style={{ margin: 0, fontSize: '1.1rem' }}>✨ AI Insights</h2>
        <button
          onClick={openStream}
          style={{
            background: 'none',
            border: '1px solid #3b82f6',
            color: '#3b82f6',
            borderRadius: 6,
            padding: '0.25rem 0.75rem',
            cursor: 'pointer',
            fontSize: '0.875rem',
          }}
        >
          Regenerate
        </button>
      </div>

      {status === 'analyzing' && (
        <p style={{ color: '#6b7280', fontStyle: 'italic' }}>Analyzing your metrics...</p>
      )}

      {(status === 'streaming' || status === 'complete') && (
        <div>
          <ReactMarkdown>{content}</ReactMarkdown>
          {status === 'complete' && (
            <p style={{ fontSize: '0.75rem', color: '#6b7280', marginTop: '1rem' }}>
              Generated by Claude
            </p>
          )}
        </div>
      )}

      {status === 'error' && (
        <p style={{ color: '#ef4444' }}>AI insights are currently unavailable.</p>
      )}
    </div>
  )
}

export default InsightsPanel
