-- GitHub Deployments
CREATE TABLE github_deployments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id   BIGINT        NOT NULL,
    repo_id     VARCHAR(255)  NOT NULL,
    environment VARCHAR(255),
    status      VARCHAR(50),
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP
);

CREATE INDEX idx_deployments_repo_created ON github_deployments (repo_id, created_at);

-- GitHub Actions Workflow Runs
CREATE TABLE github_workflow_runs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id   BIGINT        NOT NULL,
    repo_id     VARCHAR(255)  NOT NULL,
    name        VARCHAR(255),
    status      VARCHAR(50),
    conclusion  VARCHAR(50),
    head_branch VARCHAR(255),
    created_at  TIMESTAMP     NOT NULL,
    updated_at  TIMESTAMP
);

CREATE INDEX idx_workflow_runs_repo_branch_created ON github_workflow_runs (repo_id, head_branch, created_at);

-- Pull Requests
CREATE TABLE github_pull_requests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id        BIGINT        NOT NULL,
    repo_id          VARCHAR(255)  NOT NULL,
    title            VARCHAR(500),
    labels           VARCHAR(1000),
    merged_at        TIMESTAMP,
    first_commit_at  TIMESTAMP,
    merge_commit_sha VARCHAR(255),
    created_at       TIMESTAMP     NOT NULL
);

CREATE INDEX idx_pull_requests_repo_merged ON github_pull_requests (repo_id, merged_at);

-- GitHub Issues
CREATE TABLE github_issues (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id  BIGINT        NOT NULL,
    repo_id    VARCHAR(255)  NOT NULL,
    title      VARCHAR(500),
    state      VARCHAR(50),
    labels     VARCHAR(1000),
    created_at TIMESTAMP     NOT NULL,
    closed_at  TIMESTAMP
);

CREATE INDEX idx_issues_repo_created ON github_issues (repo_id, created_at);
