-- Cache metadata for GitHub API responses
CREATE TABLE github_cache_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id     VARCHAR(255) NOT NULL,
    data_type   VARCHAR(50)  NOT NULL,
    fetched_at  TIMESTAMP    NOT NULL,
    ttl_minutes INTEGER      NOT NULL DEFAULT 15
);

CREATE UNIQUE INDEX idx_cache_repo_type ON github_cache_entries (repo_id, data_type);
