-- GitHub Releases
CREATE TABLE github_releases (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    github_id    BIGINT        NOT NULL,
    repo_id      VARCHAR(255)  NOT NULL,
    tag_name     VARCHAR(255),
    name         VARCHAR(500),
    prerelease   BOOLEAN       NOT NULL DEFAULT FALSE,
    draft        BOOLEAN       NOT NULL DEFAULT FALSE,
    published_at TIMESTAMP,
    created_at   TIMESTAMP     NOT NULL
);

CREATE INDEX idx_releases_repo_published ON github_releases (repo_id, published_at);
