-- Metric Snapshots — daily persisted DORA metric values for historical trend tracking
CREATE TABLE metric_snapshots (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id        VARCHAR(255)   NOT NULL,
    metric_name    VARCHAR(100)   NOT NULL,
    window_days    INTEGER        NOT NULL,
    metric_value   DOUBLE PRECISION,
    unit           VARCHAR(100),
    band           VARCHAR(50),
    data_available BOOLEAN,
    snapshot_at    TIMESTAMP      NOT NULL,
    window_start   TIMESTAMP,
    window_end     TIMESTAMP
);

CREATE INDEX idx_snapshots_repo_metric_at ON metric_snapshots (repo_id, metric_name, snapshot_at);
